export const FETCH_DATA = 'FETCH_DATA';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const GET_FILTER_RESULT = 'GET_FILTER_RESULT';
export const ADD_FILTER_CHARECTER = 'ADD_FILTER_CHARECTER';
export const GET_DATA_ADMIN = 'GET_DATA_ADMIN';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SEARCH_RENTAL_TITLE = 'SEARCH_RENTAL_TITLE';
export const SET_SEARCH_VALUE_USERS = 'SET_SEARCH_VALUE_USERS';
export const SET_SEARCH_VALUE_RENTALS = 'SET_SEARCH_VALUE_RENTALS';

export const GET_CARD_ID = 'GET_CARD_ID';

export const SEND_USER = 'SEND_USER';
